AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy a Spring Boot application on AWS Lambda using a GraalVM native runtime.
Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
  SpringBootLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: spring-boot-graalvm-function
      Handler: bootstrap
      Runtime: provided.al2
      Code:
        S3Bucket: !Sub "spring-boot-graalvm-bucket"
        S3Key: !Sub "spring-boot-graalvm.zip"
      Role: !GetAtt LambdaExecutionRole.Arn
      MemorySize: 512
      Timeout: 30