AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Java Container with GraalVM and EFS
Parameters:
  VpcId:
    Type: String
  SubnetIds:
    Type: CommaDelimitedList
  SecurityGroupId:
    Type: String
Resources:
  ServerlessWebNativeFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 512
      FunctionName: pet-store-native
      Timeout: 15
      CodeUri: ./target/aws-lambda-java-spring-boot-sqlite-0.0.1-SNAPSHOT-native-zip.zip
      Handler: NOP
      Runtime: provided.al2023
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            TimeoutInMillis: 20000
            PayloadFormatVersion: '1.0'
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Outputs:
  ServerlessWebNativeApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/books'
    Export:
      Name: ServerlessWebNativeApi